name: Release Pipeline
on:
  push:
    branches:
      - release/*

jobs:
  build-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install --force
      - name: Read package.json
        id: package
        run: echo ::set-output name=apkName::$(node -p "require('./package.json').name")
      - name: Generate Release Asset
        run: |
          # Customize the asset generation logic here
          echo "Generating release asset..."

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.package.outputs.apkName }}-release-asset
          path: path/to/release/asset/directory
