name: Release Pipeline
on:
  push:
    branches:
      - 'release/*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
        
      - name: Get package name from package.json
        id: package-name
        run: echo "::set-output name=package-name::$(node -p "require('./package.json').name")"

      - name: Generate release notes
        id: release-notes
        run: npx auto-changelog --stdout

      - name: Configure Git identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create Git tag
        run: git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Git tag
        run: git push origin ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android/app/build/outputs/apk/release/*.apk
            README.md
            CHANGELOG.md
          body: |
            ${{ steps.package-name.outputs.package-name }} Beta
            What's Changed
            ${{ steps.release-notes.outputs.stdout }}
            New Contributors
            ${{ steps.release-notes.outputs.contributors }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
